server:
  port: 8004
spring:
  datasource:
    # serverTimezone 需要设置为 GMT+8 即为北京时间(东八区，以GMT相差8小时，%2B 为 + 号的转义符)
    url: jdbc:mysql://10.1.20.11:3306/wypt_xuty?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: JJ_passwd@2017
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl