spring:
  datasource:
    url: jdbc:mysql://10.1.20.11:3306/wypt_xuty?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
pagehelper:
  helper-dialect: mysql
  offset-as-page-num: true
  row-bounds-with-count: true
  page-size-zero: true
  reasonable: false
  support-methods-arguments: true
  params: count=countSql

# sql Êä³ö·½°¸2
logging:
  pattern:
    console: '%d -%msg%n'
  file:
    path: ./error.log
  level:
    root: debug