spring:
  datasource:
    url: jdbc:mysql://10.1.20.11:3306/wypt_xuty?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: JJ_passwd@2017
    driver-class-name: com.mysql.cj.jdbc.Driver
pagehelper:
  helper-dialect: mysql
  offset-as-page-num: true
  row-bounds-with-count: true
  page-size-zero: true
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
# 带log前缀的SQL打印输出
#logging:
#  level:
#    cn.xutingyin.mybatis.mapper: debug

#mybatis SQL语句打印
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8081
